# Generated by Django 4.2.7 on 2023-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('ssn', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
