# Generated by Django 4.2.7 on 2023-12-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoNMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobType',
            field=models.CharField(default='Nurse', max_length=40),
            preserve_default=False,
        ),
    ]
