# Generated by Django 4.2.7 on 2023-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoNMA', '0002_employee_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
