# Generated by Django 4.2.7 on 2023-12-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoNMA', '0003_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
